#ifndef Common_h
#define Common_h

#define NUM_OBJECTS_X                      128
#define NUM_OBJECTS_Y                      128
#define TOTAL_NUM_OBJECTS                  (NUM_OBJECTS_X * NUM_OBJECTS_Y)

#define MESH_THREADS_PER_THREADGROUP_POW2  5
#define MESH_THREADS_PER_THREADGROUP       (1 << MESH_THREADS_PER_THREADGROUP_POW2)
#define MESH_THREADS_PER_THREADGROUP_MASK  (MESH_THREADS_PER_THREADGROUP - 1)
#define FIRST_TP_OF_LAST_THREADGROUP       (MESH_THREADS_PER_THREADGROUP * (TOTAL_NUM_OBJECTS / MESH_THREADS_PER_THREADGROUP))
#define NUM_PRIMITIVES_OF_LAST_THREADGROUP (TOTAL_NUM_OBJECTS - FIRST_TP_OF_LAST_THREADGROUP)

#define OBJECT_THREADS_PER_THREADGROUP     1

#ifdef __METAL_VERSION__
#define DEF_CONSTANT constant
#else
#define DEF_CONSTANT static const
#endif

// TODO: Not sure #define does not work.
DEF_CONSTANT unsigned int THREADGROUPS_PER_MESHGRID = (TOTAL_NUM_OBJECTS + MESH_THREADS_PER_THREADGROUP_MASK) / MESH_THREADS_PER_THREADGROUP;


#endif /* Common_h */
