#ifndef Common_h
#define Common_h

#define NUM_PRIMITIVES_X                   128
#define NUM_PRIMITIVES_Y                   128
#define NUM_PRIMITIVES                     (NUM_PRIMITIVES_X * NUM_PRIMITIVES_Y)
#define NUM_VERTICES_PER_PRIMITIVE         3

#define MESH_THREADS_PER_THREADGROUP_POW2  5
#define MESH_THREADS_PER_THREADGROUP       (1 << MESH_THREADS_PER_THREADGROUP_POW2)
#define MESH_THREADS_PER_THREADGROUP_MASK  (MESH_THREADS_PER_THREADGROUP - 1)
#define FIRST_TP_OF_LAST_THREADGROUP       (MESH_THREADS_PER_THREADGROUP * (NUM_PRIMITIVES / MESH_THREADS_PER_THREADGROUP))
#define NUM_PRIMITIVES_OF_LAST_THREADGROUP (NUM_PRIMITIVES - FIRST_TP_OF_LAST_THREADGROUP)

#define MAX_VERTICES_PER_THREADGROUP       NUM_VERTICES_PER_PRIMITIVE * MESH_THREADS_PER_THREADGROUP
#define MAX_PRIMITIVES_PER_THREADGROUP     MESH_THREADS_PER_THREADGROUP

#define OBJECT_THREADS_PER_THREADGROUP     1

#ifdef __METAL_VERSION__
#define DEF_CONSTANT constant
#else
#define DEF_CONSTANT static const
#endif

// TODO: Not sure #define does not work.
// - It seems to be existence of too many parenthesis:
//     - WORKS:         (128 + 128)
//     - DOES NOT WORK: (128 + (128))
DEF_CONSTANT unsigned int THREADGROUPS_PER_MESHGRID = (NUM_PRIMITIVES + MESH_THREADS_PER_THREADGROUP_MASK) / MESH_THREADS_PER_THREADGROUP;

#endif /* Common_h */
