#ifndef Common_h
#define Common_h

#ifdef __METAL_VERSION__
#define CONSTANT constant const constexpr
#else
#define CONSTANT static const
#endif

CONSTANT unsigned int NUM_PRIMITIVES_X                    = 128;
CONSTANT unsigned int NUM_PRIMITIVES_Y                    = 128;
CONSTANT unsigned int NUM_PRIMITIVES                      = (NUM_PRIMITIVES_X * NUM_PRIMITIVES_Y);
CONSTANT unsigned int NUM_VERTICES_PER_PRIMITIVE          = 3;

CONSTANT unsigned int OBJECT_THREADS_PER_THREADGROUP      = 1;

CONSTANT unsigned int MESH_THREADS_PER_THREADGROUP_POW2   = 5;
CONSTANT unsigned int MESH_THREADS_PER_THREADGROUP        = (1 << MESH_THREADS_PER_THREADGROUP_POW2);
CONSTANT unsigned int MESH_THREADS_PER_THREADGROUP_MASK   = (MESH_THREADS_PER_THREADGROUP - 1);
CONSTANT unsigned int FIRST_TP_OF_LAST_THREADGROUP        = (MESH_THREADS_PER_THREADGROUP * (NUM_PRIMITIVES / MESH_THREADS_PER_THREADGROUP));
CONSTANT unsigned int NUM_PRIMITIVES_OF_LAST_THREADGROUP  = (NUM_PRIMITIVES - FIRST_TP_OF_LAST_THREADGROUP);
CONSTANT unsigned int MAX_VERTICES_PER_THREADGROUP        = NUM_VERTICES_PER_PRIMITIVE * MESH_THREADS_PER_THREADGROUP;
CONSTANT unsigned int MAX_PRIMITIVES_PER_THREADGROUP      = MESH_THREADS_PER_THREADGROUP;

CONSTANT unsigned int THREADGROUPS_PER_MESHGRID           = (NUM_PRIMITIVES + MESH_THREADS_PER_THREADGROUP_MASK) / MESH_THREADS_PER_THREADGROUP;

#endif /* Common_h */
